/**
 * generated by Xtext 2.32.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressource Need</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.RessourceNeed#getNeed <em>Need</em>}</li>
 *   <li>{@link fr.n7.pDL1.RessourceNeed#getLinkToRessource <em>Link To Ressource</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getRessourceNeed()
 * @model
 * @generated
 */
public interface RessourceNeed extends EObject
{
  /**
   * Returns the value of the '<em><b>Need</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Need</em>' attribute.
   * @see #setNeed(int)
   * @see fr.n7.pDL1.PDL1Package#getRessourceNeed_Need()
   * @model
   * @generated
   */
  int getNeed();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceNeed#getNeed <em>Need</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Need</em>' attribute.
   * @see #getNeed()
   * @generated
   */
  void setNeed(int value);

  /**
   * Returns the value of the '<em><b>Link To Ressource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link To Ressource</em>' reference.
   * @see #setLinkToRessource(Ressource)
   * @see fr.n7.pDL1.PDL1Package#getRessourceNeed_LinkToRessource()
   * @model
   * @generated
   */
  Ressource getLinkToRessource();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceNeed#getLinkToRessource <em>Link To Ressource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link To Ressource</em>' reference.
   * @see #getLinkToRessource()
   * @generated
   */
  void setLinkToRessource(Ressource value);

} // RessourceNeed
